export const COUNTRIES_LOADING = 'COUNTRIES_LOADING';
export const ADD_COUNTRIES = 'ADD_COUNTRIES';
export const COUNTRIES_FAILED = 'COUNTRIES_FAILED'

export const AIRPORTS_LOADING = 'AIRPORTS_LOADING';
export const ADD_AIRPORTS = 'ADD_AIRPORTS';
export const AIRPORTS_FAILED = 'AIRPORTS_FAILED';

export const SEARCHING_FLIGHTS = 'SEARCHING_FLIGHTS';

