export const COUNTRIES_LOADING = 'COUNTRIES_LOADING';
export const ADD_COUNTRIES = 'ADD_COUNTRIES';
export const COUNTRIES_FAILED = 'COUNTRIES_FAILED'

export const AIRPORTS_LOADING = 'AIRPORTS_LOADING';
export const ADD_AIRPORTS = 'ADD_AIRPORTS';
export const AIRPORTS_FAILED = 'AIRPORTS_FAILED';

export const SEARCHING_FLIGHTS = 'SEARCHING_FLIGHTS';

export const FLIGHTS_LOADING = 'FLIGHTS_LOADING';
export const ADD_FLIGHTS = 'ADD_FLIGHTS';
export const FLIGHTS_FAILED = 'FLIGHTS_FAILED';
export const FLIGHTS_NULL = 'FLIGHTS_NULL';

export const SINGUP_REQUEST = 'SINGUP_REQUEST';
export const SINGUP_SUCCESS = 'SINGUP_SUCCESS';
export const SINGUP_FAILED = 'SINGUP_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const OAUTH_LOGIN_SUCCESS = 'OAUTH_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST';

export const REQUEST_USER = 'REQUEST_USER';
export const ADD_USER = 'ADD_USER_SUCCESS';

export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITES = 'ADD_FAVORITES';



